Fix layout doesn't update when screen is shared
bigbluebutton/bigbluebutton pull request #12059
Opened 2021-04-16 21:04 UTC by vitormateusalmeida

Closes #11610

2021-04-16 21:17 UTC, prlanzarin requested changes

2021-04-16 21:17 UTC, prlanzarin commented on bigbluebutton-html5/imports/ui/components/layout/layout-manager/container.jsx
> +  const screenshareEntry = Screenshare.findOne({ meetingId: Auth.meetingID },
There's an identical piece of code in: https://github.com/bigbluebutton/bigbluebutton/blob/7fa9f97c74d1eca2cdb20873b03e48155afcc128/bigbluebutton-html5/imports/ui/components/screenshare/service.js#L33-L41

Can you please re-use it?

2021-04-16 21:17 UTC, prlanzarin commented on bigbluebutton-html5/private/config/settings.yml
> +    wsUrl: wss://bbb23.bbbvm.imdt.com.br/bbb-webrtc-sfu
Please revert this.

2021-04-19 13:44 UTC, daminebenq commented
Tested and works as expected. couldn't reproduce #11610 using this PR.

2021-04-19 23:47 UTC, prlanzarin approved these changes

2021-04-20 12:44 UTC, merged