Tweak viewer controls for external video component
bigbluebutton/bigbluebutton pull request #12892
Opened 2021-08-02 14:36 UTC by Tainan404

### What does this PR do?
Tweak buttons for external video player and implement viewer bahavior

Note: in mobile I added a overlay on video player, bacause the player is a Iframe and iframe doesn't propagate events to parents, so, to catch the events of `touchstart` and `touchend` I've to add it.

### Closes Issue(s)
Closes #12802

2021-08-04 20:26 UTC, lfzawacki requested changes
I'd like some changes as requested in my comments

2021-08-04 20:28 UTC, ramonlsouza commented on bigbluebutton-html5/imports/ui/components/external-video-player/component.jsx
> +    console.log('this.isMobile', this.isMobile);
^

2021-08-06 11:40 UTC, ramonlsouza requested changes
a warning is appearing for viewers:

![Screenshot from 2021-08-06 08-16-43](https://user-images.githubusercontent.com/3728706/128503860-6467611f-6da8-4ceb-96c7-ec95996fa59c.png)

video size is not the same as in develop:
![video-size](https://user-images.githubusercontent.com/3728706/128504643-336b4e23-08bb-4ab5-926d-6697205f9378.png)

can't click "play" button in mobile (because of controls overlay)

![Screenshot from 2021-08-06 08-39-11](https://user-images.githubusercontent.com/3728706/128505180-a069a63e-6a12-4906-b343-3b8fd32c3526.png)

2021-08-06 12:37 UTC, ramonlsouza approved these changes

2021-08-06 12:37 UTC, merged