test: adds Stress test
bigbluebutton/bigbluebutton pull request #12958
Opened 2021-08-09 21:09 UTC by antonbsa

### What does this PR do?
Add stress test suite and create a test that checks if the first moderator to join is the presenter

### Motivation
It took me a while to realize that some of the automated tests are failing because the first moderator is sometimes not automatically assigned as the presenter - reported in #12843.
Inspired by that, I created a test to verify this behavior. But how it will take longer and consume more memory to finish than the others, I left it separate.

I used this test as a basis to measure the following results comparing v2.3 with v2.4:
- v2.3
![join-moderator-v2 3](https://user-images.githubusercontent.com/56703993/128772958-b6fbe01f-be0b-4818-bc72-480975d60568.png)
- v2.4
![join-moderator-v2 4](https://user-images.githubusercontent.com/56703993/128772967-e6565c5c-f0f7-4324-b862-21bb9c8e18ca.png)

2021-08-10 13:12 UTC, daminebenq commented on bigbluebutton-tests/puppeteer/stress.obj.js
> +      await test.startRecording(testName);
No need to have recording enabled for stress testing.

2021-08-10 13:20 UTC, daminebenq requested changes

2021-08-10 13:20 UTC, daminebenq commented on bigbluebutton-tests/puppeteer/stress.obj.js
> +expect.extend({ toMatchImageSnapshot });
this can be removed since it's not being used

2021-08-10 13:20 UTC, daminebenq commented on bigbluebutton-tests/puppeteer/stress.obj.js
> +      await test.startRecording(testName);
No need to have recording enabled for stress testing.

2021-08-10 13:20 UTC, daminebenq commented on bigbluebutton-tests/puppeteer/stress.obj.js
> +const { toMatchImageSnapshot } = require('jest-image-snapshot');
This is about importing the visual regression libs, while it's not used here, so it should be removed.

2021-08-10 13:20 UTC, daminebenq commented on bigbluebutton-tests/puppeteer/stress/stress.js
> +      console.log(e);
Use `logger function` defined inside `core/page.js` file instead of `console.log()`

2021-08-12 15:17 UTC, MaximKhlobystov approved these changes

2021-08-12 16:09 UTC, daminebenq approved these changes

2021-08-12 16:20 UTC, merged