added drawImageProp function
bigbluebutton/bigbluebutton pull request #13855
Opened 2021-12-08 09:17 UTC by drlight17

to cover container with Virtual background instead of stretch

### What does this PR do?

This PR adds drawImageProp function to cover container with Virtual background instead of stretch (see 1st answer in https://stackoverflow.com/questions/21961839/simulation-background-size-cover-in-canvas)

### Motivation

This is fix for stretched virtual background image in case of non-standard camera aspect ratios. Image covers container instead of stretch.

### More
Compiled main meteor js for quick test is available in my repo https://github.com/drlight17/bbb-html5client-vb-cover. See README.

2021-12-08 14:04 UTC, antobinary commented
Thank you for this contribution @drlight17  !
Could you please confirm you have filled out a CLA? https://docs.bigbluebutton.org/support/faq.html#why-do-i-need-to-sign-a-contributor-license-agreement-to-contribute-source-code ?

2021-12-08 14:49 UTC, drlight17 commented
> Thank you for this contribution @drlight17 ! Could you please confirm you have filled out a CLA? https://docs.bigbluebutton.org/support/faq.html#why-do-i-need-to-sign-a-contributor-license-agreement-to-contribute-source-code ?

Oh, I almost forgot about CLA. Just sent it to ffdixon (Wed, 8 Dec 2021 17:47:43 +0300)

2021-12-08 18:34 UTC, JoVictorNunes commented
This works perfectly well. Nicely done, @drlight17!

![Captura de tela de 2021-12-08 15-32-17](https://user-images.githubusercontent.com/62393923/145264417-a25b9749-c801-4457-ba9d-a6286e9bc1ac.png)

2021-12-08 18:35 UTC, JoVictorNunes approved these changes
Works as expected!

2021-12-09 12:16 UTC, prlanzarin approved these changes

2021-12-09 12:27 UTC, JoVictorNunes requested changes
@drlight17 Could you please refactor this work so that it looks like #13865?

2021-12-09 12:52 UTC, drlight17 commented
> @drlight17 Could you please refactor this work so that it looks like #13865?

sure

2021-12-09 13:03 UTC, JoVictorNunes approved these changes

2021-12-23 19:41 UTC, merged