Improve moderator's emphasizing chat messages.
bigbluebutton/bigbluebutton pull request #14360
Opened 2022-02-14 13:32 UTC by GuiLeme

### What does this PR do?

It does 2 things in total: 
 1. It marks the message from the chat with a property called role, so that we don't use the updated user's role, instead, we use  the role on which the user sent the message.
 2. It updates the recording chat to keep track of the role changes.

The first point helps us with both keeping track of what role was the user when the message was sent,  and not re-rendering the chat on every change of users' role.
The second point is important so that we can resolve issue #13547 

Closes #14243

P.S.: This is still a WIP, I still need to change the recording files.

2022-02-17 21:34 UTC, antobinary commented
Nice work :confetti_ball: :smiley_cat:

2022-02-23 20:22 UTC, pedrobmarin commented on akka-bbb-apps/src/main/scala/org/bigbluebutton/endpoint/redis/RedisRecorderActor.scala
> +      ev.setChatEmphasizedText(msg.body.msg.chatEmphasizedText)
```suggestion
      ev.setSenderRole(msg.body.msg.sender.role)
      
      val isModerator = msg.body.sender.role == "MODERATOR"
      ev.setChatEmphasizedText(msg.body.msg.chatEmphasizedText && isModerator)
```

2022-03-10 14:10 UTC, pedrobmarin requested changes

2022-03-10 14:10 UTC, pedrobmarin commented on akka-bbb-apps/src/main/scala/org/bigbluebutton/core/apps/groupchats/SendGroupChatMessageMsgHdlr.scala
> +      userRole = user.role
Looks like this isn't used anywhere

2022-03-14 19:13 UTC, GuiLeme commented on akka-bbb-apps/src/main/scala/org/bigbluebutton/core/apps/groupchats/SendGroupChatMessageMsgHdlr.scala
> +      userRole = user.role
Definetly

2022-03-14 19:20 UTC, GuiLeme commented on bbb-common-message/src/main/scala/org/bigbluebutton/common2/msgs/GroupChatMsg.scala
> +case class GroupChatUser(id: String, name: String = "", role: String = "")
Also, done.

2022-03-15 12:19 UTC, pedrobmarin commented on akka-bbb-apps/src/main/scala/org/bigbluebutton/endpoint/redis/RedisRecorderActor.scala
> +      val isModerator = msg.body.sender.role == "MODERATOR"
```suggestion
      val isModerator = msg.body.msg.sender.role == "MODERATOR"
```
I was the one who suggested this but I didn't notice it was missing a `msg` after the `body` prop. My bad!

2022-03-15 12:23 UTC, pedrobmarin approved these changes

2022-03-16 15:36 UTC, merged