Upload presentations and still have default.pdf
bigbluebutton/bigbluebutton pull request #14944
Opened 2022-05-04 14:11 UTC by GuiLeme

### What does this PR do?

It changes the flow to preupload some documents: now with the parameter `preUploadedPresentationOverrideDefault=false`, it is possible to have the documents preuploaded along with the `default.pdf` too. 

### Closes Issue(s)

Closes #14828

2022-05-04 17:42 UTC, gustavotrott requested changes

2022-05-04 17:42 UTC, gustavotrott commented on bigbluebutton-web/grails-app/conf/bigbluebutton.properties
> +# or not (true / default)
```suggestion
# Discard default presentation (default.pdf) when Pre-upload Slides are sent within the create call (default true)
```

2022-05-05 14:01 UTC, gustavotrott commented
I was expecting `Default.pdf` to be the default (current). Once I didn't assigned any other as `current`.

https://user-images.githubusercontent.com/5660191/166939630-ed3ec2e4-002c-4292-af00-2088ff51878c.mp4

2022-05-05 18:41 UTC, GuiLeme commented
> I was expecting `Default.pdf` to be the default (current). Once I didn't assigned any other as `current`.

Yeah, I thought that if any is assigned to be current, the default flow would be executed, which is the first document in the payload batch will be the current, but I can quickly change it, no worries. So I will fix it and then make another commit, ok?

2022-05-05 20:46 UTC, GuiLeme commented
> I was expecting `Default.pdf` to be the default (current). Once I didn't assigned any other as `current`.

Already implemented, thanks for the suggestion!

2022-05-05 22:19 UTC, gustavotrott approved these changes
LGTM!

2022-05-09 15:55 UTC, antobinary commented
Hi @GuiLeme Could you please confirm it works as well when using GreenLight? ( #14828 was reported with GreenLight)

2022-05-11 22:01 UTC, gustavotrott approved these changes
Great work @GuiLeme! Working very well!

2022-05-11 22:06 UTC, merged