WIP: Integrate TLDraw with BigBlueButton
bigbluebutton/bigbluebutton pull request #14994
Opened 2022-05-11 00:57 UTC by KDSBrowne

### What does this PR do?
This PR integrates the [TLDraw ](https://github.com/tldraw) whiteboard into the html5 client.

![BBB-WB-TLDRAW](https://user-images.githubusercontent.com/22058534/167747538-d683ab2e-aab0-48e6-bf87-3982b61ef9fd.gif)

### More
This is just a draft PR as it is still work in progress while transitioning from the POC to proper integration with akka-apps. 

There are still some issues which will be addressed in near future:
- [ ] Deleting last whiteboard shape doesn't update for other users.
- [ ] Restore presentation toolbar.
- [ ] Control slide changes with previous `changeSlide` / `currentPage`.
- [ ] Button to enable and disable multiuser whiteboard for all users.
- [ ] Disable read only mode when multiuser enabled.
- [ ] Exception while invoking method persistAsset MongoServerError: After applying the update
- [ ] Following presenter's view via akka

2022-05-11 14:14 UTC, antobinary commented on bigbluebutton-html5/imports/api/audio/client/bridge/sip.js
> +        userAgentString: `BigBlueButton/${UA_SERVER_VERSION} (HTML5, rv:${UA_CLIENT_VERSION}) ${window.navigator.userAgent}`,
Looks like we may need a git rebase -- this change was done a few weeks ago, out of scope of this PR

2022-05-11 14:15 UTC, antobinary commented on bigbluebutton-html5/.meteor/versions
> +typescript@4.5.4
Let's try to upgrade React before this PR, so these changes are minimized

2022-05-11 14:16 UTC, antobinary commented on bigbluebutton-html5/package.json
> +    "react": "^17.0.2",
Let's try to upgrade React before this PR, so these changes are minimized

2022-05-11 14:17 UTC, antobinary commented on package-lock.json
> +  "lockfileVersion": 1
This file can be removed (I believe)

2022-05-11 14:22 UTC, antobinary commented on bigbluebutton-html5/imports/api/annotations/server/methods.js
> +  sendAnnotations,
```suggestion
```

duplicated line

2022-05-12 11:57 UTC, KDSBrowne commented on bigbluebutton-html5/package.json
> +    "mobx": "6.4.2",
[mobx](https://github.com/mobxjs/mobx) is the state manager used in `TLDraw`.

2022-05-13 15:05 UTC, antobinary commented on bigbluebutton-html5/imports/ui/components/whiteboard/component.jsx
> +        } catch (err) {
Should we log here or... ?

2022-05-16 13:09 UTC, ramonlsouza requested changes
- if a user leaves the whiteboard area, the cursor is not removed

https://user-images.githubusercontent.com/3728706/168598623-d701281b-724e-42d0-9c79-4af29e1534ec.mp4

- whiteboard size is different than slide size (slide does not use all available space)
![slide-size](https://user-images.githubusercontent.com/3728706/168599102-2d2236a7-6c70-4271-95a9-3ee0d041d4b6.png)

- can not move after zooming (pan tool)

https://user-images.githubusercontent.com/3728706/168599375-82416674-0947-454a-a487-80e04c77bfa4.mp4

- zoom % is not kept if user refreshes page

https://user-images.githubusercontent.com/3728706/168599524-b3a0ad69-8eba-4892-b84c-7d14df8bfa8b.mp4

- bbb crashes (for other users) if presenter refreshes

https://user-images.githubusercontent.com/3728706/168599621-106e929f-58ce-4bf8-851d-4dd2781d9c40.mp4

- “move to page” (appears when an annotation is selected) does not work as expected

https://user-images.githubusercontent.com/3728706/168599711-3e1f98cd-8a19-40a2-845b-2a7b076c37c5.mp4

2022-05-16 23:05 UTC, KDSBrowne commented
> can not move after zooming (pan tool)

I think this is a usability issue. The functionality is a little different in tldraw because there is no tool to indicate being in a pan mode. The functionality does appear to work 
![TLDRAW-PAN_ZOOM](https://user-images.githubusercontent.com/22058534/168696136-11ded72e-6328-4e58-a73e-25b43e7c1423.gif)

2022-05-20 18:57 UTC, ramonlsouza approved these changes

2022-05-20 19:51 UTC, merged