(WIP) feat: Button to transfer user to mobile App
bigbluebutton/bigbluebutton pull request #15183
Opened 2022-06-15 02:26 UTC by gustavotrott

- A new option was added when user device is iOS:
![image](https://user-images.githubusercontent.com/5660191/173722562-869e2589-2a03-4eb8-b82f-d3fd0408cdf9.png)

- The user will choose whether wants to open the BBB App (using a URL Scheme to achieve it) or if they want to open the App Store and download the App at this moment.
![image](https://user-images.githubusercontent.com/5660191/173722732-fe8e62c6-c2e7-4bf2-af87-da9ca57d0106.png)

- Once the user opens the App and connect using the same externalId, the original user will be warned about this:
![image](https://user-images.githubusercontent.com/5660191/173722833-c5073f4d-dccc-4f52-9a39-62953796bc33.png)

Closes #15091

2022-07-01 11:50 UTC, gustavotrott commented
Pending: Hide "Open in the app" button when user is already in the app.
It will be done when [15295](https://github.com/bigbluebutton/bigbluebutton/pull/15295) be merged.

2022-07-04 20:25 UTC, lfzawacki commented
Maybe we should add a setting.yml option to enable/disable this button or just skip showing it if the app url is empty.

2022-07-15 18:14 UTC, gustavotrott commented
> Maybe we should add a setting.yml option to enable/disable this button or just skip showing it if the app url is empty.

Good idea. Now the menu option will be displayed only if `iosAppStoreUrl` is not empty.

2022-07-26 10:44 UTC, gustavotrott commented
Hey @lfzawacki, are you able to take look when you have the chance?

2022-11-08 20:26 UTC, TiagoJacobs requested changes

2022-11-08 20:26 UTC, TiagoJacobs commented on bigbluebutton-html5/public/locales/en.json
> +    "app.navBar.settingsDropdown.openAppLabel": "Open in the BigBlueButton app",
Open in BigBlueButton Tablet app

2022-11-08 20:26 UTC, TiagoJacobs commented on bigbluebutton-html5/private/config/settings.yml
> +    iosAppStoreUrl: ''
Change to this value: https://apps.apple.com/us/app/bigbluebutton-tablet/id1641156756

2022-11-08 20:26 UTC, TiagoJacobs commented on bigbluebutton-html5/private/config/settings.yml
> +    iosAppUrlScheme: bigbluebutton
change to this scheme: bigbluebutton-tablet

2022-11-08 20:26 UTC, TiagoJacobs commented on bigbluebutton-html5/public/locales/en.json
> +    "app.mobileAppModal.title": "Open BigBlueButton app",
Open BigBlueButton tablet app

2022-11-08 20:26 UTC, TiagoJacobs commented on bigbluebutton-html5/public/locales/en.json
> +    "app.mobileAppModal.description": "Do you have the BigBlueButton app installed on your device?",
Do you have the BigBlueButton Tablet app installed on your device?

2022-11-08 20:26 UTC, TiagoJacobs commented on bigbluebutton-html5/imports/ui/components/nav-bar/settings-dropdown/component.jsx
> +const { isSafari, isMobileApp } = browserInfo;
Please rename this variable to be called `isTabletApp` to match the new app name

2022-11-15 12:02 UTC, TiagoJacobs commented on bigbluebutton-html5/public/locales/en.json
> +    "app.mobileAppModal.title": "Open BigBlueButton tablet app",
```suggestion
    "app.mobileAppModal.title": "Open BigBlueButton Tablet app",
```

2022-11-15 12:11 UTC, TiagoJacobs requested changes

2022-11-15 12:11 UTC, TiagoJacobs commented on bigbluebutton-web/grails-app/controllers/org/bigbluebutton/web/controllers/ApiController.groovy
> +        String query = "fullName=${fullName}&meetingID=${extId}&password=${us.role.equals(ROLE_MODERATOR) ? meeting.moderatorPassword : meeting.viewerPassword}&redirect=true&userID=${us.getExternUser
`password` parameter is deprecated in API, please use the `role` parameter instead.

2022-11-15 12:49 UTC, merged