Fix: use grails configuration for CORS settings
bigbluebutton/bigbluebutton pull request #15457
Opened 2022-07-27 21:39 UTC by schrd

### What does this PR do?

It removes quirks from bbb-web nginx config and uses grails config options to properly support CORS requests. CORS requests are only required if you run a cluster proxy setup as described in https://docs.bigbluebutton.org/admin/clusterproxy.html

### Closes Issue(s)

Closes #15436 

### Motivation

Grails can handle CORS on its own. It just has to be configured in
`/etc/bigbluebutton/bbb-web.properties`:

~~~
grails.cors.enabled=true
grails.cors.allowedOrigins=https://bbb-proxy.example.org
grails.cors.allowCredentials=true
~~~

This is a breaking change of the nginx config if (and only if) you run a
cluster setup as described in
https://docs.bigbluebutton.org/admin/clusterproxy.html

**If** you run such a setup, you **need** to change
`/etc/bigbluebutton/bbb-web.properties`. Otherwise users won't be able
to join meetings, upload slides etc.

The change in `PresentationController.groovy` fixes the handling of
`OPTIONS` requests in the `/bigbluebutton/presentation/checkPresentation`
handler.

### More

:warning: If you merge this into 2.5 operators must be warned that if they run a cluster proxy setup they must tweak their configuration
- [ ] documentation in https://docs.bigbluebutton.org/admin/clusterproxy.html has to be adjusted.
- [ ] if requiring config changes from operators is not acceptable in 2.5, the changes in `PresentationController.groovy` still fix a bug.

2022-08-18 21:02 UTC, antobinary commented
Thanks for this contribution @schrd !

We chatted about this internally and it looks like a very welcome change! We'd be looking into including this on BBB **2.6**
I am setting the milestone and am tweaking the target branch. Likely we'll need to do a [force]push or rebase but this is something that can wait until testing+final review stage (unless you do it yourself meanwhile).

I just wanted to keep you posted on the positive feedback. Thanks again!

2022-08-29 13:56 UTC, danimo commented
What's the status here?

2022-09-29 13:04 UTC, GuiLeme commented
Hello, guys, sorry for the delayed response here.

So, I tested this PR with a reverse proxy and only one instance of BBB, and there is something I want you to add in the configuration part, adjusting @schrd's comment: in `/etc/bigbluebutton/bbb-web.properties`, we must insert the BBB instance URL in the `grails.cors.allowedOrigins` property too, so it would be something like this:

```properties
grails.cors.enabled=true
grails.cors.allowedOrigins=https://bbb-proxy.example.com,https://bbb.example.com
grails.cors.allowCredentials=true
```

This fixes a connection problem with etherpad. What was happening is that bbb-web was allowed to receive requests from the proxy, but not the instance itself as it was calling the `checkAuthorization` endpoint in the API, so it ended up with a 403 error, see prints ahead:

![image](https://user-images.githubusercontent.com/69865537/193037675-feb79d0b-e7d0-4e28-af9e-c23256ab0a0c.png)

![image](https://user-images.githubusercontent.com/69865537/193037782-dcb04306-dea9-490b-8757-6c3755c54492.png)

And shared notes keeps loading: 

![image](https://user-images.githubusercontent.com/69865537/193038234-3978e5d7-26f8-4b0e-b23c-931275a24afe.png)


With the solution mentioned, all goes as expected!

2022-09-29 14:42 UTC, schrd commented
I think this is something else. Pad requests never should go through the proxy. Maybe someone is generating a URL `/pad/...` somewhere which would lead the browser to the proxy. I think instead direct connection to the BBB node should be made. I'll have a look into this.

2022-09-29 15:03 UTC, GuiLeme commented
Yeah, actually for the client to connect to the pad, it has to get the session for the etherpad component, so, I guess this request to `/pad/socket.io...` would make sense, and also, there is a request made to bbb-web to `/checkAuthorization` endpoint which gave us this CORS problem.

2022-09-29 15:38 UTC, GuiLeme commented
As I already commented on #15753 there are some fixes to do to the etherpad's files for nginx to avoid other CORS problem and resolve item B in #15436, so in #15753 we have a simple solution that could address it. 

As @schrd pointed out in https://github.com/bigbluebutton/bigbluebutton/pull/15753#issuecomment-1262385526 there may be a better solution, so we will hold this PR a bit.

2022-10-05 12:02 UTC, GuiLeme commented
> I think this is something else. Pad requests never should go through the proxy. Maybe someone is generating a URL /pad/... somewhere which would lead the browser to the proxy. I think instead direct connection to the BBB node should be made. I'll have a look into this.

@schrd, when you find it, please, respond back in this PR, so that we can properly merge it, because outside of the thing I mentioned before, it is working just fine!!

2022-11-02 21:54 UTC, schrd commented
@GuiLeme sorry for being so late. With https://github.com/alangecker/bbb-etherpad-plugin/pull/7 CORS problems in shared notes should be gone.

2023-01-10 18:41 UTC, GuiLeme commented
> @GuiLeme sorry for being so late. With https://github.com/alangecker/bbb-etherpad-plugin/pull/7 CORS problems in shared notes should be gone.

Hey @schrd, so, can we close this PR? Or is it still to be merged?

2023-01-11 07:17 UTC, schrd commented
> Hey @schrd, so, can we close this PR? Or is it still to be merged?

I think it would be still useful to have this merged. BBB works without this merge but needs ugly quirks in the nginx config which do not always work as expected (see #15436). So the purpose of this MR is pure cleanup.

2023-01-23 16:48 UTC, GuiLeme requested changes
---

2023-01-23 16:55 UTC, GuiLeme commented
Ok, so after a thorough review, it looks very good, and I don't seem to find any trouble regarding this PR.
But, I've been having some trouble while creating the cluster configured server, and so I will open an issue giving some details and if anyone wants to comment out, please do so!! Thank you!

2023-01-23 17:03 UTC, GuiLeme approved these changes
LGTM!

2023-01-23 21:54 UTC, merged