Refactor toast in presentation-uploader
bigbluebutton/bigbluebutton pull request #15474
Opened 2022-08-02 20:41 UTC by GuiLeme

### What does this PR do?

It refactors the toast to not depend on the presentation-uploader component, instead, it will be a separate component that will watch any presentation coming from the service of presentation uploader, and so, can be used in every ocasion the client wants to send a document. Moreover, it will notify the presenter of possible conversions that might be occurring, since it is watching the `Presentations` collection as well.

### Closes Issue(s)

#15259

### More

This is just a draft for now, please, do not take comments or debug logging into consideration.

2022-08-11 18:11 UTC, gustavotrott commented on bigbluebutton-html5/imports/ui/components/presentation/presentation-toast/presentation-toast-controller.js
> +		//   .map(p => p.tmpPresId)
```suggestion
```

2022-08-11 18:11 UTC, gustavotrott commented on bigbluebutton-html5/imports/ui/components/presentation/presentation-toast/presentation-toast-controller.js
> +		// UploadingPresentations.remove({tmpPresId: {$all: tmpIdconvertingPresentations}});
```suggestion
```

2022-08-11 18:13 UTC, gustavotrott commented on bigbluebutton-html5/imports/ui/components/presentation/presentation-uploader/service.js
> +  // Fazer o onConversion modificar a upload e ver o que mais da pra fazer
```suggestion
```

2022-08-11 18:14 UTC, gustavotrott commented on bigbluebutton-html5/imports/ui/components/presentation/presentation-uploader/service.js
> +  // Fazer o onConversion modificar a upload e ver o que mais da pra fazer
```suggestion
```

2022-08-16 11:25 UTC, JoVictorNunes commented on bigbluebutton-html5/imports/ui/components/presentation/presentation-uploader/component.jsx
> +          console.log("Erro aqui....", error)
```suggestion
```

2022-09-08 15:00 UTC, JoVictorNunes approved these changes
The client part seems all ok! Let's hold on @gustavotrott's review on the backend part.

2022-09-16 10:58 UTC, gustavotrott requested changes
![image(14)](https://user-images.githubusercontent.com/5660191/190623462-31437674-bffe-4aad-a98f-70fd6c5abfa9.png)

I can still reproduce the problem related in #15259.
Although this PR brings great improvements to the pres-upload toast! If you want, we can merge this changes and try to fix the problem in a subsequent PR. It seems to be related with Tldraw component only.

2022-10-05 14:37 UTC, danielpetri1 commented
Awesome stuff, after some testing it looks like https://github.com/bigbluebutton/bigbluebutton/issues/15259 and https://github.com/bigbluebutton/bigbluebutton/issues/15773 are fixed now with the latest commits! 🎉🎉 With the progress showing too!🥳

When sending a presentation to chat, however, the toast message doesn't go away once it converts. Any clues as to why that could be?

2022-10-05 15:02 UTC, merged