bbb-conf tomcat systemctl
bigbluebutton/bigbluebutton pull request #15489
Opened 2022-08-04 20:45 UTC by BrentBaccala

Only attempt TOMCAT_SERVICE systemctl operations if TOMCAT_SERVICE exists

It doesn't make sense (to me) that these systemctl operations are outside of the if blocks.

When I installed a 2.6.0-alpha.2 server, I got these messages during the install:

```
Starting BigBlueButton
Too few arguments.

# Warning:  could not be started. Please, check BBB-LTI.
#     Run the command:
#       sudo journalctl -u 
#     To better understand the ERROR

```

2022-08-04 21:00 UTC, antobinary commented
Thanks @BrentBaccala 
This seems to do similar changes to https://github.com/bigbluebutton/bigbluebutton/pull/15307

P.S. I tweaked the destination branch to be v2.6.x-release

2022-08-25 16:02 UTC, GuiLeme commented
Hey @BrentBaccala, I suggested a slight change in the code just to ensure those warnings won't break and display incomplete information.

2022-08-25 17:52 UTC, GuiLeme requested changes

2022-08-25 17:54 UTC, antobinary commented on bigbluebutton-config/bin/bbb-conf
> +        systemctl start $TOMCAT_SERVICE || {
This change has been used by others with success https://github.com/bigbluebutton/bigbluebutton/issues/15387#issuecomment-1185419014

2022-08-25 17:56 UTC, antobinary commented on bigbluebutton-config/bin/bbb-conf
> +      systemctl stop $TOMCAT_SERVICE bigbluebutton.target
```suggestion
      systemctl stop $TOMCAT_SERVICE
```

2022-08-25 17:56 UTC, antobinary commented on bigbluebutton-config/bin/bbb-conf
> -    systemctl stop $TOMCAT_SERVICE bigbluebutton.target
systemctl stop bigbluebutton.target

2022-08-25 17:57 UTC, antobinary commented on bigbluebutton-config/bin/bbb-conf
> -    systemctl stop $TOMCAT_SERVICE bigbluebutton.target
(otherwise we won't stop BBB if TOmcat is not present)

2022-08-26 14:50 UTC, antobinary commented
I just pushed https://github.com/bigbluebutton/bigbluebutton/pull/15489/commits/e15c1711ea3417f72087fec7dbef193a527fc869 into this PR and am merging. Thanks @BrentBaccala and @GuiLeme

2022-08-26 14:50 UTC, merged

2022-09-07 08:14 UTC, paulmenzel commented
Sorry, a little bit off-topic, but how can this merge/pull request be reviewed? There are 127 commits shown and 80 files changed.

2022-09-07 12:48 UTC, antobinary commented
@paulmenzel that is my fault - I pushed a commit into this branch and had not noticed I was carrying extra commits. Let me see if I can do anything now to keep the actual changes

2022-09-07 12:58 UTC, paulmenzel commented
@antobinary, thank you. Stuff happens, so no worries. Just wanted to make sure, I didn’t miss anything. Interested people can use the git command line.

2022-09-07 12:59 UTC, antobinary commented
Brent opened a pull request with only https://github.com/BrentBaccala/bigbluebutton/commit/29adba9a030c1293bb2f8bf786c083710ed6f31f
@GuiLeme suggested https://github.com/BrentBaccala/bigbluebutton/commit/21b08db177c2c2f1f5cab8e5b6c7fe426ceb7e7a and I included it
And then I pushed https://github.com/BrentBaccala/bigbluebutton/commit/e15c1711ea3417f72087fec7dbef193a527fc869 into it too ..
So altogether it forms... https://github.com/bigbluebutton/bigbluebutton/compare/v2.6.0-alpha.2...antobinary:total-tomcat-changes?expand=1