fix(external videos) youtube shorts link working
bigbluebutton/bigbluebutton pull request #15784
Opened 2022-10-05 16:01 UTC by Carloshsc

### What does this PR do?

Validates if the url is from youtube shorts and change the url 'shorts' to 'watch'.

### Screenshots

https://user-images.githubusercontent.com/39932802/194107200-a1df029e-babe-4c61-909f-6b47a31a7aea.mp4

2022-10-05 16:51 UTC, lfzawacki requested changes

2022-10-05 19:31 UTC, lfzawacki approved these changes

2022-10-06 14:58 UTC, MaximKhlobystov commented
Hi @Carloshsc,

Thank you for this contribution! Could you please confirm if you already sent in the signed Contributor License Agreement? See https://docs.bigbluebutton.org/support/faq.html#why-do-i-need-to-sign-a-contributor-license-agreement-to-contribute-source-code. Thanks in advance!

2022-10-16 14:33 UTC, ffdixon commented
@Carloshsc Can you send a signed contributor license agreement to cla .at. bigbluebutton .dot. org.  See https://docs.bigbluebutton.org/support/faq.html#why-do-i-need-to-sign-a-contributor-license-agreement-to-contribute-source-code.

2022-10-28 14:30 UTC, merged