New nginx rules
bigbluebutton/bigbluebutton pull request #15977
Opened 2022-11-09 18:05 UTC by Tainan404

### What does this PR do?

limit parrallel connections for a same ws url to improve performance

2022-11-09 19:40 UTC, TiagoJacobs requested changes

2022-11-09 19:40 UTC, TiagoJacobs commented on build/packages-template/bbb-config/after-install.sh
> +sed -i '/include \/etc\/nginx\/conf\.d\/\*\.conf\;/ a \\tlimit_conn_zone $uri zone=ws_zone:5m;' /etc/nginx/nginx.conf
In order to keep it easy to maintain, I propose that you do it like this:
```
echo 'limit_conn_zone $uri zone=ws_zone:5m;' > /etc/nginx/conf.d/html5-conn-limit.conf
```

PS: I haven't tested, please check if it works.

2022-11-09 20:17 UTC, merged

2022-12-30 17:25 UTC, danimo commented
Hey, I would like to understand how this patch improves performance, and where. Can you shed some light? If I understand the directives correctly, a maximum of three calls to the WS endpoint can be made from any given IPv4 address within five minutes. This sounds like this could introduce subtle issues with traffic from behind an IPv4 NAT or CGNAT router at the very latest, e.g. in hybrid teaching scenarios or with all students using the same ISP on CGNAT.

2023-01-09 13:14 UTC, Tainan404 commented
Hi @danimo, The WS endpoint is unique per user, the PR limits the number of parallel connections of an user for the same URL (it doesn't impact users from the same network), I think the 5 minutes you're talking about is the `5m` in the zone declaration, it doesn't related to time but to the shared memory size for registering the connections `5m` means 5 megabytes. I hope I've clarified a little, any questions feel free to talk. :)