add delay for shared note true unmount
bigbluebutton/bigbluebutton pull request #16072
Opened 2022-11-30 17:00 UTC by Tainan404

### What does this PR do?

Add a delay to truely unmount the shared notes, when the shared notes is unmounted the connection with the etherpad is closed ans takes a few second to reconnect, delaying it we hold the connection when the user is navigating through other panels (chat, poll and etc)

### Motivation

Remove the speed bump though the navigation to another panels.

### More
2.6

https://user-images.githubusercontent.com/15806883/204860716-4289a01c-4cc8-48d0-9530-9958892a16db.mp4

PR:

https://user-images.githubusercontent.com/15806883/204860813-ac7e12ff-8780-4eec-926b-221ec0ed3db0.mp4

2023-01-09 17:59 UTC, ramonlsouza commented on bigbluebutton-html5/imports/ui/components/notes/component.jsx
> +  console.log();
```suggestion
```

2023-01-09 17:59 UTC, ramonlsouza commented on bigbluebutton-html5/imports/ui/components/notes/component.jsx
> +console.log(DELAY_UNMOUNT_SHARED_NOTES);
```suggestion
```

2023-01-09 18:03 UTC, ramonlsouza requested changes
"write closed captions" and "pin notes onto whiteboard" features are not working correctly

[Screencast from 2023-01-09 14-53-54.webm](https://user-images.githubusercontent.com/3728706/211375824-18d8c7e8-f8aa-4c67-ba04-1408c6d80043.webm)

[Screencast from 2023-01-09 14-57-32.webm](https://user-images.githubusercontent.com/3728706/211376202-53fef49e-fd86-4155-95e4-07c9eda6c95a.webm)

2023-01-19 14:49 UTC, ramonlsouza approved these changes

2023-01-19 14:51 UTC, merged

2023-01-19 15:04 UTC, antobinary commented on bigbluebutton-html5/private/config/settings.yml
> +    delayForUnmountOfSharedNote: 120000
Could you please add an inline comment stating what this is (and what it means to reduce/increase the value; also -- milliseconds?)