Cleanning unused docker images
bigbluebutton/bigbluebutton pull request #16659
Opened 2023-02-07 11:52 UTC by GuiLeme

### What does this PR do?

It just cleans unused docker images on a daily basis. By doing that, it removes folders with plenty of data inside `/var/lib/docker/overlay2` directory

### Closes Issue(s)

Closes #16381

2023-02-07 17:50 UTC, gustavotrott commented
Hey, the command `docker rmi $(docker images --filter "dangling=true" -q --no-trunc)` returns error when there is no untagged and unamed images.

![image](https://user-images.githubusercontent.com/5660191/217324110-f4817889-9b67-4052-8815-85eecf07031a.png)

What do you think about use `docker images --filter "dangling=true" -q --no-trunc | xargs -r docker rmi` instead?

![image](https://user-images.githubusercontent.com/5660191/217324644-e554d6f6-c72e-485f-86f0-8e4da8b2e2a5.png)

2023-02-07 18:08 UTC, GuiLeme commented
> What do you think about use docker images --filter "dangling=true" -q --no-trunc | xargs -r docker rmi instead?

Yeah, that could totally work, I will test and make necessary changes!

2023-02-08 16:42 UTC, gustavotrott approved these changes
lgtm

2023-02-08 17:12 UTC, gustavotrott requested changes
Avoid to use `-f` in `docker rmi` command

2023-02-09 00:22 UTC, gustavotrott approved these changes
lgtm

2023-02-09 01:20 UTC, merged