allowModsToUnmuteUsers fix
bigbluebutton/bigbluebutton pull request #17054
Opened 2023-03-15 19:04 UTC by paultrudel

### What does this PR do?

Removes the `user.locked` condition on `allowedToUnmuteAudio` that was preventing moderators from being able to unmute users.

### Closes Issue(s)
Closes #16759

2023-03-28 17:04 UTC, ramonlsouza requested changes
Could you change the `!user.locked` to `!userLocked` (defined in [line 337](https://github.com/bigbluebutton/bigbluebutton/blob/v2.6.x-release/bigbluebutton-html5/imports/ui/components/user-list/user-list-content/user-participants/user-list-item/component.jsx#L337)) instead of removing it? It should correctly check if the user is locked and not a moderator

2023-03-29 13:36 UTC, paultrudel commented
> Could you change the `!user.locked` to `!userLocked` (defined in [line 337](https://github.com/bigbluebutton/bigbluebutton/blob/v2.6.x-release/bigbluebutton-html5/imports/ui/components/user-list/user-list-content/user-participants/user-list-item/component.jsx#L337)) instead of removing it? It should correctly check if the user is locked and not a moderator

Changing `!user.locked` to `!userLocked` still prevents moderators from being able to unmute attendees. Additionally, moderators are able to unmute themselves, as well as other moderators, but attendees cannot unmute themselves. Switching it to `userLocked` instead leads to moderators being able to unmute attendees, but not themselves or any other moderators, and attendees can also unmute themselves but no one else.

2023-03-29 14:08 UTC, ramonlsouza commented
> Changing `!user.locked` to `!userLocked` still prevents moderators from being able to unmute attendees. Additionally, moderators are able to unmute themselves, as well as other moderators, but attendees cannot unmute themselves. Switching it to `userLocked` instead leads to moderators being able to unmute attendees, but not themselves or any other moderators, and attendees can also unmute themselves but no one else.

Oooh I see now that `getAvailableActions` already checks if the user is a moderator, so it is ok to remove `!user.locked`. Sorry!!

2023-03-29 14:12 UTC, ramonlsouza approved these changes

2023-03-30 13:11 UTC, merged