Fix: Cameras don't obstruct buttons anymore.
bigbluebutton/bigbluebutton pull request #17705
Opened 2023-04-24 20:03 UTC by Scroody

### What does this PR do?

This PR fixes the issue where the cameras were obstructing buttons.

### Closes Issue(s)

#17703

2023-04-25 08:16 UTC, trinhhuutam commented
Should we use px instead of pt? That will fix the issue without * 0.75

2023-04-25 11:09 UTC, KDSBrowne commented
If we use `px` here it will crash iphones

2023-04-25 16:12 UTC, trinhhuutam commented
> If we use `px` here it will crash iphones. Maybe switch to `pt` only when iphones are detected.

Yes! Has tried with px and it causes crash on iPhone again. I'm using z index for (+) button to work-around this issue .

2023-04-25 16:49 UTC, antonbsa commented
I just tested, no iPhone crashes were found! However, the whiteboard cursor is slightly offset when the cameras are positioned above or on the left of the presentation:


https://user-images.githubusercontent.com/56703993/234346862-be0acfdd-5654-4b26-9719-eda0213728c0.mp4

2023-04-25 23:42 UTC, trinhhuutam commented
> dex for (+) button to work-around this issue when waiting official fix from you.

Btw, can you help to explain why use px here cause crash on Iphone only? I have to tried to find out but found nothing.
Does it cause crash on other elements with width height using px too?

2023-04-26 17:50 UTC, SamuelWei commented on bigbluebutton-html5/imports/ui/components/webcam/component.jsx
> +  const camOpcity = isDragging ? 0.5 : undefined;
```suggestion
  const camOpacity = isDragging ? 0.5 : undefined;
```

2023-04-26 17:51 UTC, SamuelWei commented on bigbluebutton-html5/imports/ui/components/webcam/component.jsx
> +                opacity: camOpcity,
```suggestion
                opacity: camOpcity,
```
Fix typo, see other comment

2023-04-26 17:51 UTC, SamuelWei requested changes
Fix variable spelling typo

2023-04-26 17:56 UTC, antonbsa approved these changes
Re-tested and working as expected! No error logs or crashes, both on desktop and mobile

2023-04-26 18:13 UTC, merged

2023-05-02 07:18 UTC, jorgelondo commented
Hi, someone can help me with the location of that file  "component.jsx" on the server to be able to make that change while the latest release comes out, because it's really urgent for me to make that change. thank you