Refactor: Chat using graphql and pagination
bigbluebutton/bigbluebutton pull request #17876
Opened 2023-05-11 14:45 UTC by Tainan404

### What does this PR do?

This PR introduces the graphql to the chat messages in BBB, with the new pagination we stabilzed pages and load it incrementaly as the user request to look into the message history, not storing more the whole chat history in client memory.

### Motivation

Make the chat support graphql and make use of pagination to improve client performance

2023-05-11 20:05 UTC, gustavotrott commented
![image (2)](https://github.com/bigbluebutton/bigbluebutton/assets/5660191/03d01a71-bac7-4ad8-89c8-da894e44f5c9)

It seems that it is missing one message between two pages.
Maybe you need to tweak the offset.

2023-05-11 20:09 UTC, gustavotrott commented
https://github.com/bigbluebutton/bigbluebutton/assets/5660191/a0848fff-8a57-40f4-a8fb-b533331e1703

When I scroll down a little, the scroll bar jumps directly to bottom.

2023-05-11 20:36 UTC, gustavotrott commented
https://github.com/bigbluebutton/bigbluebutton/assets/5660191/4e99afd3-9a2e-41b2-bea3-4f082c0ec8ee

I'm stopped at the top, and other users are sending msg.
When a new page is created, my current page changes (while I'm reading it..).

2023-05-16 13:40 UTC, TiagoJacobs commented on bigbluebutton-html5/imports/ui/components/chat/chat-graphql/chat-message-list/component.tsx
> +  const chatId = !isPublicChat ? idChatOpen : PUBLIC_GROUP_CHAT_KEY;
For a reduced cognitive effort, please change it to:
```
  const chatId = isPublicChat ? PUBLIC_GROUP_CHAT_KEY : idChatOpen;
```

2023-05-16 13:43 UTC, TiagoJacobs commented on bigbluebutton-html5/imports/ui/components/chat/chat-graphql/chat-message-list/component.tsx
> +  const currentChat = chatData?.chat?.filter((chat) => chat?.chatId === chatId)?.[0];
Use `find` instead `filter()[0]`.

Example:

```js
[1,2,3,4,5].find(function (el) {
    return el > 3;
});
```

2023-05-16 14:52 UTC, TiagoJacobs requested changes
Hello! 

I propose that we remove the old meteor code in this PR (instead of just adding the graphql code).

The old code will always be available in git history / 2.6.x branches.

2023-05-16 18:01 UTC, gustavotrott commented
When I just open the chat, it always loads the page 1.
And then immediately remove it and load the last and last-1 pages.

https://github.com/bigbluebutton/bigbluebutton/assets/5660191/f88c1da4-ca89-4961-8e88-19b690fb80bb

I think it shouldn't waste bandwidth downloading the first page if it will not be shown.
And it also shows a weird switch of content.

### - Second 00:46 shows message 50
![image](https://github.com/bigbluebutton/bigbluebutton/assets/5660191/0a4ce56d-a9ec-4366-83dc-da1e4a6b80e8)

### - Second 00:47 hides that page
![image](https://github.com/bigbluebutton/bigbluebutton/assets/5660191/462be03e-eafd-4468-ad32-c64c31451da7)

### - Second 00:48 shows message 1012
![image](https://github.com/bigbluebutton/bigbluebutton/assets/5660191/2b62864f-d1f5-412f-ba50-0a6bf61cffcc)

2023-05-17 19:33 UTC, gustavotrott approved these changes
lgtm! great job, the chat is really seamless in this new version!

2023-05-18 18:09 UTC, merged