Port Mconf Timer into BBB 2.7
bigbluebutton/bigbluebutton pull request #17941
Opened 2023-05-18 19:49 UTC by Arthurk12

### What does this PR do?

This PR ports our Mconf Timer feature into BBB 2.7:

The timer feature is a useful tool that enables presenters or moderators to start a synchronized time counting across multiple clients.

The timer feature has 2 modes: Stopwatch and Timer itself.
- **Stopwatch** is the default one and it counts foward without a limit time.
- In **Timer** mode, set an initial time and it counts down to 0. If timer.alarm is true, an alarm will sound when the time ends.

There are 3 pre-selected songs that can be played along with the timer in Timer mode. They are configured in `settings.yml` file as well as their volume.
Also, if `timer.tabIndicator` is set to true in the `settings.yml` file the current time is displayed in the tab's title.

New variables added to the `settings.yml`:
```
  timer:
    enabled: true
    alarm: true
    music:
      enabled: true
      volume: 0.4
      track1: "RelaxingMusic"
      track2: "CalmMusic"
      track3: "aristocratDrums"
    interval:
      clock: 100
      offset: 60000
    time: 5
    tabIndicator: true
```

![timer](https://github.com/bigbluebutton/bigbluebutton/assets/32987232/fd8d8f28-32bd-406b-b3d2-42948f1929cc)

2023-05-18 20:00 UTC, antobinary commented
Wow! Well done! :clap:

2023-06-07 20:49 UTC, GuiLeme requested changes
It is working just fine. I just made some suggestions regarding good practices. Overall great job!!

2023-06-07 20:49 UTC, GuiLeme commented on bigbluebutton-html5/imports/ui/components/user-list/user-list-content/component.jsx
> +        { isTimerActive && <TimerContainer
There are some ES-lint warnings in this file

2023-06-07 20:49 UTC, GuiLeme commented on bigbluebutton-html5/public/locales/en.json
> +    "app.timer.timer.label": "Timer",
```suggestion
    "app.timer.title": "Time",
    "app.timer.stopwatch.title": "Stopwatch",
    "app.timer.timer.title": "Timer",
```
Those are not used anymore

2023-06-07 21:11 UTC, antobinary commented on bigbluebutton-html5/imports/api/timer/index.js
> +  Timer._ensureIndex({ meetingId: 1 });
Careful with the backtick ` in the suggested change. Otherwise - fair suggestion, thanks!

2023-06-08 16:47 UTC, antobinary commented
FYI @GuiLeme is working on applying the suggested changes.

2023-06-08 19:56 UTC, merged