refactor(bbb-web): Use Tika as MIME type detection tool
bigbluebutton/bigbluebutton pull request #18030
Opened 2023-05-29 13:29 UTC by danielpetri1

### What does this PR do?
Detects the media type of a given presentation using [Tika](https://tika.apache.org/2.8.0/index.html), which bases its detection method on the document content and potential known file extensions.

The goal is to prevent container formats such as `.docx` and `.pptx` from simply returning e.g. `application/zip` as their `MIME` type, which was occurring when the `file` bash command encountered malformed presentations.

Left as draft so that bringing in Tika as a content analysis toolkit can be discussed with @gustavotrott and @GuiLeme.

### Closes Issue(s)
#17737
#17824
Potentially #17122 (untested)

### More
Removed catch-all antipattern, use of exceptions for regular control flow, and redundant defensive programming. Fixed a few typos throughout related code.

2023-05-30 11:37 UTC, gustavotrott commented
Note for @antobinary,

If we merge this PR, we can remove the dependency of `file` on bbb install.

2023-05-30 19:28 UTC, ffdixon commented
There are some sample files in https://github.com/bigbluebutton/bigbluebutton/issues/17737 to test against.

2023-06-05 15:38 UTC, GuiLeme requested changes
Just those 2, but overall it's really good!

2023-06-07 13:05 UTC, GuiLeme requested changes

2023-06-07 14:57 UTC, danielpetri1 commented on bbb-common-web/src/main/java/org/bigbluebutton/presentation/SupportedFileTypes.java
>  import java.io.BufferedReader;
Thanks, fixed.

2023-06-07 15:30 UTC, GuiLeme approved these changes
LGTM!

2023-06-07 16:41 UTC, merged