Client change: List the option to download presentation with annotations even if there are no annotations
bigbluebutton/bigbluebutton pull request #18130
Opened 2023-06-08 18:18 UTC by Scroody

### What does this PR do?

This PR makes the non annotated presentation also show the download button.

Closes #

#18101

2023-06-08 18:39 UTC, gustavotrott commented on bigbluebutton-html5/imports/ui/components/presentation/presentation-uploader/presentation-download-dropdown/component.jsx
> +          },
Why is this part inside the `if (hasAnnotations) {` if it always happens?
Move it outside the condition and avoid duplicating code!

2023-06-16 12:40 UTC, GuiLeme requested changes
One last thing is to not specify in the chat that the presentation has annotations. I would just put `default.pdf` without `(with annotations)` 

![image](https://github.com/bigbluebutton/bigbluebutton/assets/69865537/9d065134-6570-455f-b182-c751683fa118)

2023-06-16 12:40 UTC, GuiLeme commented on bigbluebutton-html5/imports/ui/components/presentation/presentation-uploader/presentation-download-dropdown/component.jsx
> +        this.menuItems.push({
Consider removing the annotated download button from both if's (`if (!isDownloadable) {` and `if (hasAnnotations) {`) as it works independently of the downloadable status of the presentation and annotations count now.

2023-06-16 12:40 UTC, GuiLeme commented on bigbluebutton-html5/imports/ui/components/presentation/presentation-uploader/presentation-download-dropdown/component.jsx
> +          label: intl.formatMessage(intlMessages.sendAnnotatedDocument),
Since it may not contain annotations anymore, I think a better label for it would be "Send out a download link of the current presentation state."

2023-06-23 17:17 UTC, ramonlsouza requested changes
"send download link" should be available if download of original presentation is enabled 


https://github.com/bigbluebutton/bigbluebutton/assets/3728706/81442665-0565-4666-955d-5caa6e27903c

2023-06-26 19:27 UTC, ramonlsouza approved these changes

2023-06-26 19:27 UTC, merged