Screen wake lock feature
bigbluebutton/bigbluebutton pull request #18164
Opened 2023-06-13 19:27 UTC by Arthurk12

### What does this PR do?

This PR adds the screen wake lock feature, which is available only for mobile users using browser with support to the given API.
When an user with a supported device joins the meeting, a toast is displayed offering to activate the feature.
Adds a toggle under settings menu to activate/deactivate it.

New settings.yml flag `enableWakeLock` default is `false`
![wake_lock_feature](https://github.com/bigbluebutton/bigbluebutton/assets/32987232/782ab4e9-01d5-46f4-8926-58b85d21d685)

2023-06-13 20:43 UTC, antobinary reviewed
Great addition, thank you @Arthurk12 !

I left a few comments.

2023-06-13 20:43 UTC, antobinary commented on bigbluebutton-html5/private/config/settings.yml
> +    enableWakeLock: false
Should we leave only one of the configs?

2023-06-13 20:43 UTC, antobinary commented on bigbluebutton-html5/imports/ui/components/wake-lock/component.jsx
> +          { button1 }
Do we have more descriptive names?

2023-06-13 20:43 UTC, antobinary commented on bigbluebutton-html5/imports/ui/components/wake-lock/component.jsx
> +      request().then((success) => {
Is `success` here acting like an `error`?

2023-06-13 20:43 UTC, antobinary commented on bigbluebutton-html5/imports/ui/components/wake-lock/service.js
> +  isEnabled: () => WakeLock.isEnabled(),
```suggestion
  isEnabled: () => wakeLock.isEnabled(),
```

2023-06-14 15:29 UTC, antobinary commented on bigbluebutton-html5/private/config/settings.yml
> +    enableWakeLock: false
For whether the feature is enabled or not, let's mimic how other [recent] features do it -- see darkMode for example,

```
featureName
  enabled: Boolean
```

2023-07-14 12:34 UTC, ramonlsouza requested changes
If I choose "Yes!" it says that the feature is active, but in settings it appears as OFF.

https://github.com/bigbluebutton/bigbluebutton/assets/3728706/45e16c1d-5ed2-4d86-a8fc-459fe4c34025

2023-07-27 13:54 UTC, ramonlsouza approved these changes

2023-07-27 13:58 UTC, merged