Client: Timer added as disabled feature
bigbluebutton/bigbluebutton pull request #18163
Opened 2023-06-13 18:55 UTC by Scroody

### What does this PR do?

This PR adds the timer feature to the list of disabled features.

### Closes Issue(s)

#18137

2023-06-13 20:36 UTC, antobinary commented
Please also add this addition in api.md (see how it was mentioned in 2.6)
![Screenshot from 2023-06-13 16-34-29](https://github.com/bigbluebutton/bigbluebutton/assets/6312397/9c065410-123a-4b05-b6d3-5c78b84ca46b)

2023-06-14 15:10 UTC, GuiLeme requested changes
I also think there might need some changes in `akka` to prevent any interactions of the timer from the back-end. I can do a PR to your branch.

2023-06-14 15:10 UTC, GuiLeme commented on bigbluebutton-html5/imports/ui/services/features/index.js
> +  return getDisabledFeatures().indexOf('timer') === -1 && Meteor.settings.public.timer;
```suggestion
  return getDisabledFeatures().indexOf('timer') === -1 && Meteor.settings.public.timer.enabled;
```
Also, consider changing other places in the code where `Meteor.settings.public.timer` is being used to use this `isTimerFeatureEnabled` function.

2023-06-15 14:43 UTC, GuiLeme approved these changes
LGTM!

2023-06-15 14:45 UTC, GuiLeme commented on bigbluebutton-html5/imports/ui/components/actions-bar/actions-dropdown/component.jsx
>    makePresentationItems() {
It's decided to not fix more lint errors in this PR

2023-06-15 14:46 UTC, GuiLeme commented on bigbluebutton-html5/imports/ui/components/actions-bar/actions-dropdown/component.jsx
>    }
> It's decided to not fix more lint errors in this PR

See comment above

2023-06-15 20:31 UTC, gustavotrott commented
@GuiLeme , I think it's enough to validate `CreateTimerReqMsgHdlr` on the backend.
Not necessary to repeat the validation for every action!

2023-06-21 18:32 UTC, antobinary commented on docs/docs/development/api.md
> +- **create** - **Added:**  Added `timer`, `cameraAsContent` and `snapshotOfCurrentSlide` as options for `disabledFeatures=`.
```suggestion
- **create** - **Added:**  Added `timer`, added `disabledFeatures` options`cameraAsContent` and `snapshotOfCurrentSlide`.
```

2023-06-21 18:33 UTC, merged

2023-06-21 18:37 UTC, gustavotrott commented
Related https://github.com/bigbluebutton/bigbluebutton/issues/14203