conf: Check for necessary permissions in bbb-conf
bigbluebutton/bigbluebutton pull request #18317
Opened 2023-07-13 17:59 UTC by lkiesow

Running `bbb-conf` as an unprivileged user will give you a lot of errors and a broken result:

```
❯ bbb-conf --secret
grep: /etc/bigbluebutton/bbb-web.properties: Permission denied
grep: /usr/share/bbb-web/WEB-INF/classes/bigbluebutton.properties: Permission denied
grep: /etc/bigbluebutton/bbb-web.properties: Permission denied
grep: /usr/share/bbb-web/WEB-INF/classes/bigbluebutton.properties: Permission denied
grep: /etc/bigbluebutton/bbb-web.properties: Permission denied
grep: /usr/share/bbb-web/WEB-INF/classes/bigbluebutton.properties: Permission denied
/usr/bin/bbb-conf: line 206: /etc/bigbluebutton/bbb-web.properties: Permission denied
grep: /etc/bigbluebutton/bbb-web.properties: Permission denied
grep: /usr/share/bbb-web/WEB-INF/classes/bigbluebutton.properties: Permission denied
grep: /etc/bigbluebutton/bbb-web.properties: Permission denied
grep: /usr/share/bbb-web/WEB-INF/classes/bigbluebutton.properties: Permission denied

    URL: /bigbluebutton/
    Secret:

    Link to the API-Mate:
    https://mconf.github.io/api-mate/#server=/bigbluebutton/&sharedSecret=
```

This patch makes the tool check for read permissions on one of the protected configuration files. If the user has permissions to access that file, things should be fine. If not, complain and fail fast.

2023-07-14 11:34 UTC, antobinary commented
Thank you!

2023-07-14 11:44 UTC, antobinary requested changes
Hmm, the CI process failed at the installation step. Perhaps we should check if the file exists and then if it's readable...

2023-07-17 10:16 UTC, lkiesow commented
I can skip the check if the configuration files does not exist.

The alternative would be to simply check if you run the script either as `root` or as user `bigbluebutton`. Only those two should have the necessary permissions.

What do you think?

2024-07-15 19:26 UTC, antobinary commented
Actually, sudo/root permissions are only needed for write type of operations, so --setsecret, etc
checking the --status I believe should not require elevated permissions.

2025-07-11 21:54 UTC, closed without merging