feature: User list dropdown plugin
bigbluebutton/bigbluebutton pull request #18607
Opened 2023-08-22 12:51 UTC by GuiLeme

### What does this PR do?

It adds support  for the new extensible Area of `UserListDropdownItem` and also for the `useLoadedUserList` hook from the Plugin Architecture.

Lastly, it corrects some issues spotted from the previous iteration on the plugin architecture on the extensible area (PresentationToolbarPlugin).

### More

For now it is just a draft, it is waiting for the merge of https://github.com/bigbluebutton/bigbluebutton-html-plugin-sdk/pull/9

2023-08-23 12:42 UTC, TiagoJacobs requested changes

2023-08-23 13:34 UTC, GuiLeme commented on bigbluebutton-html5/imports/ui/components/user-list/user-list-content/user-participants/user-list-participants/user-actions/component.tsx
> +  isOptionEmpty: boolean | undefined;
I thought about it too, but it seems that letting `isOprionEmpty` gives us a more generic property, that could be used not only to mount a separator. But on the other hand, for now, we only have the separator option, so, what do you say?

2023-08-23 13:43 UTC, GuiLeme commented on bigbluebutton-html5/imports/ui/components/plugins-engine/plugin-provided-state/container.tsx
> +  }, [presentationToolbarItems, userListDropdownItems]);
Hum, I don't know about that. I think the way it is written, it seems readable already and besides it avoids code duplicate (it wouldn't be much really, just the  `setPluginsProvidedAggregatedState` supposedly).

What we could do is separate those into two different files, like perhaps `plugin-provided-state/presentation-toolbar/container.tsx` and `plugin-provided-state/user-list-dropdown/container.tsx`. What do you say?

2023-08-23 22:56 UTC, TiagoJacobs commented on bigbluebutton-html5/imports/ui/components/user-list/user-list-content/user-participants/user-list-participants/user-actions/component.tsx
> +  isOptionEmpty: boolean | undefined;
We have one property named `divider`, and another named `dividerTop`.

However the plugin is calling it as `separator`, and treating it as a different item, which I appreciate.

So I would propose that you modify the existing code to prepend an item like `{separator: true}` for the cases that are now using `dividerTop: true`. Same thing for appending when it's `divider: true`.

This way we clean-up these different terms in the existing code, and make it more compatible with how the plugin is working.

2023-08-29 12:05 UTC, Tainan404 requested changes

2023-08-31 21:34 UTC, Tainan404 approved these changes
LGTM

2023-09-04 18:43 UTC, TiagoJacobs approved these changes
LGTM

2023-09-04 19:10 UTC, TiagoJacobs commented
Hello @GuiLeme - just for helping others in the future, can you remove this part of your PR description, and replace it by instructions on how to try it?

![image](https://github.com/bigbluebutton/bigbluebutton/assets/2075267/a78caea2-ebf6-4f89-afa2-387b8964229f)

@ramonlsouza - after that you can try to run it, and if everything goes well, we can merge!

2023-09-05 12:49 UTC, ramonlsouza approved these changes

2023-09-05 12:49 UTC, merged