refactor: add isSeparator option as a menu item
bigbluebutton/bigbluebutton pull request #18638
Opened 2023-08-24 15:05 UTC by GuiLeme

### What does this PR do?

It adds the option `isSeparator` to the `BBBMenu` items so that it enhances readability in the code.

### Motivation

Not only it will enhance readability but it will also give us another type of item to work with in the menus. It will specially be useful for PR https://github.com/bigbluebutton/bigbluebutton/pull/18607 where one of the possible menu items the plugin developer can choose is the separator itself.

2023-08-24 23:30 UTC, TiagoJacobs commented on bigbluebutton-html5/imports/ui/components/audio/audio-graphql/audio-controls/input-stream-live-selector/buttons/LiveSelection.tsx
> +  isSeparator?: boolean;
As here you are in typescript, you should have two different types, one for the `DeviceListItemType` other for the `Separator`.

/cc @Tainan404

2023-08-29 13:03 UTC, TiagoJacobs requested changes
Hello @GuiLeme 

For each modified menu, please create 2 gif's (one showing the menu without this PR - in `develop` branch) and the other showing the menu with this PR (in your `refactor-bbb-menu` branch).

Thank you!

2023-09-04 15:07 UTC, TiagoJacobs approved these changes
LGTM

2023-09-04 16:05 UTC, ramonlsouza approved these changes

2023-09-04 16:06 UTC, merged