Refactor: Migrate timer indicator
bigbluebutton/bigbluebutton pull request #18838
Opened 2023-09-25 13:07 UTC by Tainan404

### What does this PR do?

Migrate the Timer indicator to use TS + Graphql

2023-09-26 20:46 UTC, ramonlsouza requested changes
time format is not the same as in 2.7

3.0
![timer-30](https://github.com/bigbluebutton/bigbluebutton/assets/3728706/dda894e6-bdb1-4bb8-8631-0ad2980275c3)

2.7
![timer-27](https://github.com/bigbluebutton/bigbluebutton/assets/3728706/a5a076be-983c-4417-80c1-44a41026786e)

"reset" button is not working

https://github.com/bigbluebutton/bigbluebutton/assets/3728706/9a789ac7-cb02-415c-b318-ec4cc273bb68

2023-10-10 14:45 UTC, ramonlsouza approved these changes

2023-10-10 15:23 UTC, GuiLeme requested changes
I spotted an issue:
The time indicator has inconsistency when stopping it for stopwatch.

**To Reproduce:**
- Open Stopwatch;
- Start the clock;
-  See the time indicator running correctly;
- Try to stop it either by clicking on stop on the stopwatch sidebar or by clicking the time indicator;
- See inconsistency;

See demo of what happens:

https://github.com/bigbluebutton/bigbluebutton/assets/69865537/8c0d0fa6-5d7e-43cd-a815-0f7245078f9b

2023-10-10 17:41 UTC, GuiLeme approved these changes
LGTM!

2023-11-01 16:55 UTC, antonbsa approved these changes

2023-11-02 11:06 UTC, merged