fix: Null pointer exception when parent meeting does not exist
bigbluebutton/bigbluebutton pull request #18986
Opened 2023-10-19 19:57 UTC by paultrudel

### What does this PR do?

Performs a check when creating a breakout room through the API to see if the parent meeting exists.

### Motivation

Currently no check is done to see if the meeting corresponding to the provided `parentMeetingID` actually exists which can lead to an error.

### More

- [ ] Added/updated documentation

2023-10-19 20:24 UTC, antobinary commented
Follow up from https://github.com/bigbluebutton/bigbluebutton/pull/18975

2023-10-20 12:13 UTC, gustavotrott commented on bigbluebutton-web/grails-app/controllers/org/bigbluebutton/web/controllers/ApiController.groovy
> +    if(params.isBreakout == "true") {
```suggestion
    Boolean isBreakoutRoom = false
    if (!StringUtils.isEmpty(params.isBreakout)) {
      isBreakoutRoom = Boolean.parseBoolean(params.isBreakout)
    }

    if(isBreakoutRoom) {
```

2023-10-20 12:13 UTC, gustavotrott commented on bigbluebutton-web/grails-app/controllers/org/bigbluebutton/web/controllers/ApiController.groovy
> +      if(!params.parentMeetingID) {
```suggestion
      if(StringUtils.isEmpty(params.parentMeetingID)) {
```

2023-10-20 12:14 UTC, gustavotrott requested changes
Let's follow the pattern used to read other params.

2023-10-20 13:23 UTC, gustavotrott approved these changes

2023-10-20 13:24 UTC, merged