Refactor: Migrate external video player
bigbluebutton/bigbluebutton pull request #19074
Opened 2023-11-06 15:04 UTC by Tainan404

### What does this PR do?

Same of #18909, but made in 3.0 branch, the first version were meant to develop branch having a few conflicts when changed to 3.0 so a made a new branching cherry picking the commits

2023-11-07 15:42 UTC, antonbsa approved these changes
tested and everything is working properly! LGTM

2023-11-07 18:34 UTC, ramonlsouza requested changes
"play the video to enable media synchronization" message appears to the viewer even if the video is already playing

https://github.com/bigbluebutton/bigbluebutton/assets/3728706/b9d6b94d-9fce-429b-b673-01c3f2202d42

2023-11-07 19:57 UTC, antonbsa requested changes
also: I've re-installed my local container, double-checked this feature, and found that in case the user clicks on "start a new video" without any URL, the following attempt containing a URL will open broken - it would be fixed by keeping the button disabled until there's a valid URL

https://github.com/bigbluebutton/bigbluebutton/assets/56703993/7f103ff5-f07c-460f-a6c9-80ee20134760

2023-11-08 18:48 UTC, antonbsa approved these changes

2023-11-09 13:01 UTC, ramonlsouza approved these changes

2023-11-09 13:42 UTC, merged