Adds new layouts for specific integration scenarios
bigbluebutton/bigbluebutton pull request #19208
Opened 2023-11-24 14:22 UTC by vitormateusalmeida

### What does this PR do?

This PR adds 3 new layouts: "Cameras Only", "Presentation Only", and "Participants and Chat Only", as requested in issue #18879. The layouts are not visible to the user and can only be activated via custom parameters. To improve these layouts, some issues need to be addressed:

Should the hidden features in each layout remain hidden? For example, in "Cameras Only", should controls such as displaying the user list, opening presentations, sharing screens, etc., be hidden?
In the "Presentation Only" layout, does external video and screen sharing count as part of the presentation?
In the "Participants and Chat Only" layout, should the components take up the entire screen?
These questions have not been resolved as they are not part of the scope of the task and are considered as improvements.

### Closes Issue(s)
Closes #18879

### Preview
<details>
<summary>Cameras Only</summary>

![image](https://github.com/bigbluebutton/bigbluebutton/assets/9675166/ab19cca4-88bf-47b6-9abb-bfa70d86f59e)
</details>

<details>
<summary>Presentation Only</summary>

![image](https://github.com/bigbluebutton/bigbluebutton/assets/9675166/7d49635b-d6d4-409f-a9e4-7a2ac798ff7a)
</details>

<details>
<summary>Participants and Chat Only</summary>

![image](https://github.com/bigbluebutton/bigbluebutton/assets/9675166/3a118199-3fda-419a-91af-3e92b6007188)
</details>

2023-11-24 15:29 UTC, TiagoJacobs commented
> Should the hidden features in each layout remain hidden? For example, in "Cameras Only", should controls such as displaying the user list, opening presentations, sharing screens, etc., be hidden?

Yes, controls that will not work (like display user list when layout is cameras only) must be hidden.

> In the "Presentation Only" layout, does external video and screen sharing count as part of the presentation?

Yes, as it refers to the presentation area.


> In the "Participants and Chat Only" layout, should the components take up the entire screen?

Yes, as in the opposite we would have an empty space, which would be very weird. 

---

I see that all these items are needed in order to merge the pr, because if we merge like these, the layouts could be considered broken/with bugs.

Thanks @vitormateusalmeida 



I understand that we should not me

2023-11-26 15:42 UTC, vitormateusalmeida commented
@ramonlsouza 
In the "LayoutModalComponent," I added a filter to ignore the added layouts that should not appear in the layout selection modal.
It would be better if there were a flag to identify layouts that should or should not appear in the list. For example, layouts to be used with "enforceLayout" should not appear.
Please check line 110 of the LayoutModalComponent.

2023-11-27 11:33 UTC, ramonlsouza commented on bigbluebutton-html5/imports/ui/components/layout/layout-manager/camerasOnly.jsx
> +    );
This function expects no arguments

```suggestion
    const mediaBounds = calculatesMediaBounds();
```

2023-11-27 11:35 UTC, ramonlsouza commented on bigbluebutton-html5/imports/ui/components/layout/layout-manager/participantsChatOnlyLayout.jsx
> +    );
This function expects no arguments

```suggestion
    const cameraDockBounds = calculatesCameraDockBounds();
```

2023-11-27 11:35 UTC, ramonlsouza commented on bigbluebutton-html5/imports/ui/components/layout/layout-manager/presentationOnlyLayout.jsx
> +    );
This function expects no arguments

```suggestion
    const cameraDockBounds = calculatesCameraDockBounds();
```

2023-11-27 11:38 UTC, ramonlsouza requested changes
Nice PR! I suggested some changes based on SonarCloud report

2023-11-28 09:39 UTC, ramonlsouza approved these changes

2023-11-28 09:40 UTC, merged