fix: Improve Arrow Shape Handling With Tldraw v2
bigbluebutton/bigbluebutton pull request #19376
Opened 2024-01-02 14:42 UTC by KDSBrowne

### What does this PR do?
This PR enhances the whiteboard's arrow shape functionality by transferring the arrow shape cleaning logic from the client to the backend (Akka). This shift addresses and resolves an intermittent race condition.

### Motivation
Prevents the following error, thereby improving the stability of the whiteboard.

![image](https://github.com/bigbluebutton/bigbluebutton/assets/22058534/d5f121c9-b399-4a71-b574-01e690de8c22)

2024-01-22 16:26 UTC, antobinary commented on akka-bbb-apps/src/main/scala/org/bigbluebutton/core/apps/WhiteboardModel.scala
> +    println(s"addAnnotations - Before: ${wb.annotationsMap}")
Please drop the logs if this is a final version

2024-01-22 16:27 UTC, antobinary commented on akka-bbb-apps/src/main/scala/org/bigbluebutton/core/apps/WhiteboardModel.scala
> +    println(s"addAnnotations - After: ${newWb.annotationsMap}")
please drop this log as it will likely be impacting performance

2024-01-22 16:29 UTC, antobinary commented on akka-bbb-apps/src/main/scala/org/bigbluebutton/core/apps/WhiteboardModel.scala
> +    println(s"deleteAnnotations - After: ${updatedWb.annotationsMap}")
Another pair of logs to be dropped if this is ready for merging

2024-01-23 11:45 UTC, gustavotrott commented on akka-bbb-apps/src/main/scala/org/bigbluebutton/core/apps/WhiteboardModel.scala
> +    println(s"deleteAnnotations - Before: ${wb.annotationsMap}")
```suggestion
```

This print is flooding the logs.

2024-01-23 11:48 UTC, gustavotrott commented on akka-bbb-apps/src/main/scala/org/bigbluebutton/core/apps/WhiteboardModel.scala
>          }
```suggestion
        println(s"Annotation $annotationId not found.")
```

2024-01-23 11:49 UTC, gustavotrott requested changes
Apart from the unnecessary logs, it looks good!

2024-01-23 15:36 UTC, merged