Refactor: migrate poll answer gathering
bigbluebutton/bigbluebutton pull request #19421
Opened 2024-01-11 16:54 UTC by JoVictorNunes

### What does this PR do?

Migrate poll answer gathering from Meteor to GraphQL.

2024-01-22 20:17 UTC, JoVictorNunes commented
> polling container remains open after voting for an anonymous poll

@ramonlsouza Fixed by https://github.com/bigbluebutton/bigbluebutton/pull/19421/commits/b7fac7bfc048d58be86dbbacbbf82b59de494e19 and https://github.com/bigbluebutton/bigbluebutton/pull/19482/commits/1757c0b2f1ea11f20fc77bd4ac894d4e7e543d32.

2024-01-23 14:33 UTC, Tainan404 requested changes

2024-01-23 14:33 UTC, Tainan404 commented on bigbluebutton-html5/imports/ui/components/polling/polling-graphql/component.tsx
> +import PollService from '/imports/ui/components/poll/service';
Prefer implements it on own service to isolate the component or move it on global scope

2024-01-23 14:33 UTC, Tainan404 commented on bigbluebutton-html5/imports/ui/components/polling/polling-graphql/component.tsx
> +import AudioService from '/imports/ui/components/audio/service';
move the AudioService to your service.ts, make it easier in future to remove.

2024-01-23 14:33 UTC, Tainan404 commented on bigbluebutton-html5/imports/ui/components/polling/polling-graphql/component.tsx
> +import { isPollingEnabled } from '/imports/ui/services/features';
Move it to service for the same reason of the AudioSettings

2024-01-23 14:33 UTC, Tainan404 commented on bigbluebutton-html5/imports/ui/components/polling/polling-graphql/component.tsx
> +interface PollingGraphqlContainerProps {}
Whay to have a empty declarion of an interface

2024-01-23 17:08 UTC, Tainan404 approved these changes
LGTM!

2024-01-23 17:28 UTC, merged