Client: System message style
bigbluebutton/bigbluebutton pull request #19514
Opened 2024-01-25 15:10 UTC by Scroody

### What does this PR do?

This PR gives the majority of system messages a new look. As suggested by @TiagoJacobs in my previous PR: #19203.

### Motivation

The motivation for this PR to happen is to make clear for the user that those messages are provided by the system.

### Examples

Before -
![image](https://github.com/bigbluebutton/bigbluebutton/assets/36093456/a790f384-8ddd-4c72-bda0-ec95191bb63a)

After - 
![image](https://github.com/bigbluebutton/bigbluebutton/assets/36093456/5b5c6710-822a-471f-8a3a-ed7a4ebb2025)

OBS: I took the liberty to alter the clear chat message aswell, because both are system messages and should follow the same pattern.
In the 'What does this PR do?' section I mentioned the "majority" of system messages and that's because I din't change the breakout room moderator message: 
![image](https://github.com/bigbluebutton/bigbluebutton/assets/36093456/e1bb4412-3344-4dec-9ffc-f9c27e0eb79b)

The reason I didn't alter this one is because they are completely different system messages and their behavior differs a lot.

2024-01-25 17:58 UTC, gabriellpr approved these changes

2024-01-26 17:21 UTC, ramonlsouza commented on bigbluebutton-html5/imports/ui/components/chat/chat-graphql/chat-message-list/page/chat-message/component.tsx
> +  const clearMessage = `${intl.formatMessage(intlMessages.chatClear)} at ${msgTime}`;
![2024-01-26_14-18](https://github.com/bigbluebutton/bigbluebutton/assets/3728706/8e17bca6-5dbe-432f-9de4-a5f4fda5191a)

the "at" part is not going to be translated to other languages

2024-01-26 17:24 UTC, ramonlsouza commented on bigbluebutton-html5/imports/ui/components/chat/chat-graphql/chat-message-list/page/chat-message/component.tsx
> +  const msgTime = dateTime.toLocaleTimeString('en-US', { hour: 'numeric', minute: 'numeric', hour12: true });
if we're localizing the time string, it should be localized to the same locale the user is currently using, the same way it is done now
en: 2:23 PM
pt-br: 14:20

![2024-01-26_14-23](https://github.com/bigbluebutton/bigbluebutton/assets/3728706/95929d1a-ae86-4ed7-af98-f0ad9d6455be)
![2024-01-26_14-20](https://github.com/bigbluebutton/bigbluebutton/assets/3728706/22434a32-935c-4230-9b5c-3970c018c8da)

2024-01-26 17:27 UTC, ramonlsouza requested changes
1. can we use all available space when displaying a system message? notice the empty space on the left side
2. user name and time is not appearing even for user-sent messages

![2024-01-26_14-25](https://github.com/bigbluebutton/bigbluebutton/assets/3728706/60357f55-a4a1-4be3-ab03-52cbdb5cab95)

2024-01-29 20:17 UTC, gabriellpr approved these changes

2024-01-29 20:19 UTC, merged