docs: info on allowOverrideClientSettingsOnCreateCall
bigbluebutton/bigbluebutton pull request #19919
Opened 2024-03-27 20:57 UTC by antobinary

### What does this PR do?
- adds info on `allowOverrideClientSettingsOnCreateCall`
- sets a safer default value

### Closes Issue(s)

Closes #none
Related: https://github.com/bigbluebutton/bigbluebutton/pull/18782

TODO:
- [ ] Add an example how to use, elaborate on the api docs page.

2024-03-27 23:50 UTC, TiagoJacobs commented on bigbluebutton-web/grails-app/conf/bigbluebutton.properties
> +# Enable this option to avoid overriding client settings through /create call
Enable this option to avoid overriding -> Enable this option to **allow** overriding

2024-03-28 00:01 UTC, antobinary commented on bigbluebutton-web/grails-app/conf/bigbluebutton.properties
> +# Enable this option to avoid overriding client settings through /create call
```suggestion
# Enable this option to allow overriding client settings through /create call
```

Thanks @TiagoJacobs

2024-03-28 20:54 UTC, GuiLeme requested changes

2024-03-28 20:54 UTC, GuiLeme commented on docs/docs/data/create.tsx
> +    "description": (<>**Note: this can be used only via POST create call** (added in BBB 3.0.0-alpha.1)</>)
Please, remove this line.

2024-03-28 20:55 UTC, GuiLeme commented on docs/docs/data/create.tsx
> +    "description": (<>**Note: this can be used only via POST create call** (added in BBB 3.0.0-alpha.1)</>)
The parameter can be passed via GET

2024-04-15 15:57 UTC, antobinary commented on docs/docs/data/create.tsx
> +    "description": (<>**Note: this can be used only via POST create call** (added in BBB 3.0.0-alpha.1)</>)
```suggestion
    "description": (<> (added in BBB 3.0.0-alpha.1)</>)
```

2024-05-10 02:12 UTC, antobinary commented on docs/docs/new-features.md
> +`graphqlWebsocketUrl=${bigbluebutton.web.serverURL}/v1/graphql` added
```suggestion
`graphqlWebsocketUrl=${bigbluebutton.web.serverURL}/graphql` added
```

https://github.com/bigbluebutton/bigbluebutton/pull/20193

2024-05-10 02:15 UTC, merged