Add: connection status for graphql connection
bigbluebutton/bigbluebutton pull request #20196
Opened 2024-05-08 13:46 UTC by Tainan404

### What does this PR do?
Add a connection status handler for graphql connection, add a limit of attempts for reconnections, show a error when limit reached.

2024-05-08 14:02 UTC, antobinary commented on bigbluebutton-html5/public/locales/en.json
> +    "app.reconnectingMessage": "Disconnected. Trying to reconnect.",
Looks like we can remove next line - `"app.retryNow": "Retry now",`

2024-05-09 19:50 UTC, antonbsa approved these changes

2024-05-09 23:37 UTC, antobinary requested changes
See above

2024-06-10 20:04 UTC, antonbsa approved these changes

2024-06-10 20:20 UTC, merged