fix(plugins): fix useUserCameraDomElement behavior and did some refactor
bigbluebutton/bigbluebutton pull request #21004
Opened 2024-08-22 14:12 UTC by GuiLeme

### What does this PR do?

- Adds new extensible area: userCameraHelper (which is a button added in one of the corners of the user camera);
- Fixes useUserCameraDomElement (the issue was that when a new user enters the room, the dom-element-manipulator hook didn't return the elements);
- Adds a click event to the arguments of the onClick callback function of screenshareHelper;
- Refactors naming of plugin hook events so as to add new event informing bbb-core that the plugin is changing something on its side; 

### More

This PR is closely related to the SDK https://github.com/bigbluebutton/bigbluebutton-html-plugin-sdk/pull/110

See a demo of the new userCameraHelper down below:

![image](https://github.com/user-attachments/assets/9e9b0f21-0c69-47ab-8a1f-fc029f9be05b)

2024-09-04 17:54 UTC, Arthurk12 requested changes

2024-09-04 19:20 UTC, germanocaumo requested changes
Missing displayFunction in UserCameraHelperItems

2024-09-04 19:20 UTC, germanocaumo commented on bigbluebutton-html5/imports/ui/components/video-provider/video-list/video-list-item/component.tsx
> +          pluginItems.map((pluginItem) => {
Missing the displayFunction filter here
```suggestion
          pluginItems.filter(
            (pluginItem) => (pluginItem.displayFunction?.({ userId, streamId }) ?? true),
          ).map((pluginItem) => {
```

2024-09-04 19:20 UTC, germanocaumo commented on bigbluebutton-html5/imports/ui/components/video-provider/video-list/video-list-item/component.tsx
> +  pluginItems: UserCameraHelperInterface[],
```suggestion
  pluginItems: UserCameraHelperButton[],
```

2024-09-10 17:55 UTC, Arthurk12 approved these changes
LGTM.

2024-09-10 18:18 UTC, merged