fix(dark-theme): adjust Dark Reader CSS selectors
bigbluebutton/bigbluebutton pull request #21074
Opened 2024-08-30 15:50 UTC by Arthurk12

### What does this PR do?
Clean up inverted css selectors passed to Dark Reader and add new ones for elements not correctly transformed to dark theme. These include the tldraw color picker, text shape color, selected color indicator, tool opacity slider, and camera dock background.
Comparsion:
Before and after:
![whiteboard_](https://github.com/user-attachments/assets/d9dae401-f9ba-49b5-8f34-a76b49e8caa4) ![whiteboard](https://github.com/user-attachments/assets/19350cae-99ab-48ff-afa3-cfc45c337b72)
![cameraDock-background_](https://github.com/user-attachments/assets/43a39943-ef5a-4b53-9f23-feb6818189fa)
![cameraDock-background](https://github.com/user-attachments/assets/4cdd45b8-0582-476e-968a-1b5ed350e7dc)

2024-09-04 16:31 UTC, gabriellpr approved these changes

2024-09-06 19:31 UTC, germanocaumo requested changes
Found some wrong colors, suggested changes to fix

2024-09-06 19:31 UTC, germanocaumo commented on bigbluebutton-html5/imports/ui/components/whiteboard/component.jsx
> +    }
From my tests this didn't seem to make a difference, did you notice it not applying sometimes?

2024-09-06 19:31 UTC, germanocaumo commented on bigbluebutton-html5/imports/ui/components/app/styles.js
> +  .tl-html-container > div.tl-text-shape__wrapper.tl-text-shadow
More selectors to add to fix notes and text colors inside shapes (mainly arrows)
```suggestion
  .tl-html-container > div.tl-text-shape__wrapper.tl-text-shadow,
  .tl-text,
  .tl-text-input,
  .tl-text-content,
  .tl-text-label__inner,
  .tl-note__container,
  .tl-text.tl-text-content,
  .tl-arrow-label,
  .tl-arrow-label__inner
```

2024-09-06 19:31 UTC, germanocaumo commented on bigbluebutton-html5/imports/ui/components/app/styles.js
>    #connectionBars > div
Some fixes to note background color and caret color
```suggestion
  #connectionBars > div,
  .tl-note__scrim,.tl-arrow-label[data-isediting="true"] > .tl-arrow-label__inner {
    background-color: unset !important;
  }
  textarea {
    caret-color: black !important;
  }
```

2024-09-06 19:31 UTC, germanocaumo commented on bigbluebutton-html5/imports/ui/components/app/styles.js
>    }
This is needed to fix background color in pdfs with transparent background 
```suggestion
  .tl-container {
    .tl-image {
      background-color: white !important;
    }
  }
```

2024-09-10 10:08 UTC, germanocaumo requested changes

2024-09-10 10:08 UTC, germanocaumo commented on bigbluebutton-html5/imports/ui/components/whiteboard/component.jsx
> +    }
@Arthurk12 yeah I think it's better to remove it, not needed in this tldraw version

2024-09-16 09:34 UTC, germanocaumo approved these changes

2024-09-16 12:49 UTC, merged