fix(chat): Loading a new message page freezes the client
bigbluebutton/bigbluebutton pull request #21521
Opened 2024-10-24 13:55 UTC by JoVictorNunes

### What does this PR do?

- When the user clicks `Load more messages` the client freezes for a few seconds before rendering the new page. This was happening because the message component was overheaded with hook calls and data access which were triggering an additional render. In order to fix that, all those hook calls within the message component were placed in the parent component (more stable, doesn't rerender frequently) and passed as props to the message component.

### Closes Issue(s)

n/a

### How to test

1. Start a session.
2. Go to the chat.
3. Type 100+ messages.
4. Scroll up and click 'Load more messages'.

2024-10-24 20:14 UTC, gustavotrott commented
does it close the issue #21434?

2024-10-25 11:26 UTC, JoVictorNunes commented
> does it close the issue #21434?

Maybe. I'm not sure yet. Even though they are the same problem, #21434 happens in a different scenario. I'm doing some testing to see if this PR closes it.

2024-10-28 18:25 UTC, Arthurk12 requested changes
The performance when toggling the chat panel and loading previous chat pages has significantly improved, reducing loading time. However, I've noticed that when a new message is sent, all messages on the last page are being re-rendered (see gif below). It seems the trigger for this issue might be the callback ref passed to the `ChatMessage` component, which is instantiated each time the component renders.

![issue](https://github.com/user-attachments/assets/8bb1ca94-8b19-4c90-99df-c22c7fece4bb)

2024-10-29 11:33 UTC, JoVictorNunes commented on bigbluebutton-html5/imports/ui/components/chat/chat-graphql/chat-message-list/page/component.tsx
>              ref={(ref) => {
Nice catch!

2024-10-29 14:06 UTC, Arthurk12 approved these changes

2024-10-29 17:47 UTC, merged