!build: Use the default postgresql version (14) for Ubuntu 22.04
bigbluebutton/bigbluebutton pull request #21629
Opened 2024-11-06 21:21 UTC by antobinary

### What does this PR do?

Switches the required version for `postgresql` from the recently added 17
to the version which comes with Ubuntu 22.04 -- `postgresql-14`

### Closes Issue(s)

Closes #21441 
Together with  https://github.com/bigbluebutton/bbb-install/pull/759 closes #21386 

### Motivation

When we/I added the code from https://github.com/bigbluebutton/bbb-install/pull/759
that allowed for postgres to get upgraded on reruns of bbb-install.sh
See #21386 for the mess that created (basically no predictability on which postgres you are using)
Also that meant we could not reliably override configs for postgres - see #21441 

https://github.com/bigbluebutton/bigbluebutton/pull/21588 was an attempt to add predictability
however, we could still not guarantee that version 17 would be used if bbb-install.sh was to silently pull version 18 later on.

Switching back from 17 to 14 allows us to stick to a major version
without having to _pin_ (risking missing important patches)
It also means some hassle when upgrading to BBB 3.0.0-beta.5 if you were running an earlier BBB 3.0
It also means though, that we give up on any performance gains/new functionality for Postgres after 14

### How to test

### More

- [ ] When https://github.com/bigbluebutton/bbb-install/pull/759 is merged, update the bbb-install.sh command for CI here.

2024-11-09 00:43 UTC, TiagoJacobs requested changes
Hello @gustavotrott 

Postgresql in BBB is used only for holding the ephemeral data of currently running meetings.

Said that, I would advocate for using `docker run --rm ` to start postgres, and stop relying on the version that comes with ubuntu.

This gives us the maximum flexibility for running the version we want.

Also, this avoids situations like someone installing BBB and using postgresql for something else.

So my recomendation would be:

- Move postgresql to a container (and keep version 17)
- Use a non standard port (so we avoid the situation I described above)

This will also ensure that the database will be cleaned when `bbb-conf --restart` is executed.

What do you think?

2024-11-28 17:44 UTC, antobinary commented on .github/workflows/automated-tests.yml
> +          wget -nv https://raw.githubusercontent.com/bigbluebutton/bbb-install/ubuntu-version-of-postgres/bbb-install.sh -O bbb-install.sh
```suggestion
          wget -nv https://raw.githubusercontent.com/bigbluebutton/bbb-install/v3.0.x-release/bbb-install.sh -O bbb-install.sh
```

2024-11-28 17:49 UTC, gustavotrott commented
I support to merge this PR as a "revert" of forcing pg 17. Once old installations are not being able to upgrade the `bbb-graphql-server` package:

![image](https://github.com/user-attachments/assets/f30aac88-9946-4ea4-b5a7-fe298efc5d40)

We can continue the discuss of Dockerized Postgres idea for next release.

2024-11-28 19:21 UTC, gustavotrott commented
Merging as is to fix PG 17 requirement.
A subsequent PR will address @TiagoJacobs's comment.

2024-11-28 19:21 UTC, merged